### ISSUE TITLE
ticking entity crash when attempting to access network

### ISSUE THREAD

**Issue by cainamar** [badasintended/slotlink#74] opened 2021-02-16 23:23 UTC
**Setup**
- Minecraft: 1.16.5
- Fabric API: 0.30.0
- slotlink: 2.2.0
- expanded storage version: 5.6.32

**Problem**
just started a new network with only four connections and it instantly crashes when right clicking the storage request block
Crash report: https://pastebin.com/7V9eHU6R

**Reproduction**
just four double gold chests from expanded storage hooked up to the controller with the request block on top of the controller

![image](https://user-images.githubusercontent.com/53030836/108134206-c864ad80-7083-11eb-80bb-2784ea34ad78.png)

![image](https://user-images.githubusercontent.com/53030836/108134244-dd414100-7083-11eb-8606-7c2fe0683ff2.png)

**Remarks**
modpack is https://www.curseforge.com/minecraft/modpacks/euphoriccuriosity
with dank storage and xaero's world/minimap added

**Comment by deirn** [comment] 2021-02-16 23:30
duplicate of #71
Update NBT Crafting https://github.com/Siphalor/nbt-crafting/issues/64

**Closed by deirn** 2021-02-16 23:30 UTC
Labels: bug
