### ISSUE TITLE
Dupe glitch using link cables

### ISSUE THREAD

**Issue by OweningIt** [badasintended/slotlink#40] opened 2020-08-23 12:46 UTC
**Setup**
- Minecraft: 1.16.1
- Fabric API: abric-api-0.17.0+build.386-1.16.1.jar
- slotlink: 1.0.3
- related mod: VERSION

**Problem**
When the system is unloaded, changes made to it are not saved, leading to the ability to dupe, and void items
This bug was experienced on the all of fabric 3 modpack on a server

**Reproduction**
Just a standard storage network setup, then unloading the chunks leads to the glitch

**Remarks**
I am unsure if this is fixed in newer versions, but I couldn't find anything saying that it was

**Comment by Adirelle** [comment] 2020-08-24 10:04
@OweningIt How do you access the storage ? With a Remote from afar ? Could this be related to chunk containing the Netowork Master being unloaded ? Or the containers (chests) ? Does using a chunkloader fix it ?

**Comment by OweningIt** [comment] 2020-08-24 10:24
Yes, using a chunkloader solved it
But I'm not sure whether it is related to the master or the cheats

**Comment by deirn** [comment] 2020-08-31 02:32
it's somewhat fixed on 76bb3a0 by forceloading chunks before opening the network, but then it introduces server overload, especially if you use the remote. It'll delay the opening to 10 sec at most, but not freezing the client so you can walk and stuff.     

my idea is to forceload when your hotbar selects the remote, and unload when changed to another item, though I don't know if its a good idea. another idea is to send a c2s packet so the server can forceload it asynchronously.

**Comment by Adirelle** [comment] 2020-08-31 07:51
Considering you can automate things with importer and exporter cables, I am wondering if force-loading the chunk containing the master and those cable would be a good idea or not. On one hand, it would allow to easily fix . On the other hand, this is a on load on the server and you could delegate it to another mod that provides chunk loader blocks.

**Comment by deirn** [comment] 2020-08-31 10:27
it'll definitely affect server performance on a large network in multiple chunks, but the average network won't exceed 3x3 chunk, 5x5 at most, so I guess it's fine? kinda?

the problem is whether forceloading only when needed (opening remote) is worth it more than always forceloading chunks with slotlink blocks..., but then people will abuse it and use the block for forceloading since it is cheaper to craft :P

**Comment by Adirelle** [comment] 2020-08-31 16:57
Forceloading only on remote use (not even selecting) is probably the best approach to avoid abuse. Just make sure it includes both the master and the linked containers.

**Comment by deirn** [comment] 2020-09-01 05:21
4d35652 seems significantly reduced the delay and overload, might as well release it and let people try it since I'm only tested in on local server.

**Comment by deirn** [comment] 2020-09-01 10:26
@OweningIt since I don't have the resource to run a dedicated server, I need you to try 1.2 yourself and open another ticket if there's an issue with this approach.

**Closed by deirn** 2020-09-01 10:26 UTC
Labels: bug
